### ISSUE TITLE
False positive on `NoUnused.CustomTypeConstructorArgs`

### ISSUE THREAD

**Issue by ShrykeWindgrace** [jfmengels/elm-review-unused#14]
False positive on `NoUnused.CustomTypeConstructorArgs` if a type is declared in one module and its constructors are pattern-matched in another module.

**SSCCE (Short Self-Contained Correct Example)**
I created a gist to illustrate the issue: 
https://gist.github.com/ShrykeWindgrace/6ed0fd9335cfa9e200da68674bedfccb

`elm-review` in this project results in 
```bash
- ELM-REVIEW ERROR -------------------------------------- src/Messages.elm:5:15

NoUnused.CustomTypeConstructorArgs: Argument is never extracted and therefore
never used.

4| type Msg
5|     = Content String
                 ^^^^^^
6|     | Search String

This argument is never used. You should either use it somewhere, or remove it at
the location I pointed at.

────────────────────────────────────────────────────────── src/Messages.elm:6:14

NoUnused.CustomTypeConstructorArgs: Argument is never extracted and therefore
never used.

5|     = Content String
6|     | Search String
                ^^^^^^

This argument is never used. You should either use it somewhere, or remove it at
the location I pointed at.

I found 2 errors in 1 file.
```
even though we explicitly pattern-match on constructors and use the deconstructed value in the `update` function in the `Main` module. The documentation for this rule explicitly mentions `==` and `/=` operators without deconstruction, but as far as I understand we are not in this case.

**Expected behavior**
No error reported.

**Additional context**
`"elm-review": "2.3.2"`
`"jfmengels/elm-review-unused": "1.1.2"`

**Comment by jfmengels** [comment]
Thanks for the report and the SSCCE, this was very helpful!
This should be fixed in v1.1.3. The problem was due to a bug in `jfmengels/elm-review`, so the patch here was fixing the issue there and bumping the dependency to that new version (v2.3.3)

**Comment by ShrykeWindgrace** [comment]
Thanks a lot for this prompt fix!

**Comment by jfmengels** [comment]
My pleasure 🙂
When you have the time, I'd love confirmation that the issue has been fixed for you!

**Comment by ShrykeWindgrace** [comment]
I have just checked - indeed, with
```
            "jfmengels/elm-review": "2.3.3",
            "jfmengels/elm-review-unused": "1.1.3",
```
in `review/elm.json` I no longer see any false positives.

**Comment by jfmengels** [comment]
Awesome! Thanks for letting me know :blush:
