### ISSUE TITLE
NoUnused.Patterns: Tuple pattern is not needed. (This is not true)

### ISSUE THREAD

**Issue by kutyel** [jfmengels/elm-review-unused#22]
**Describe the bug**
Elm-review reports tuple patterns not needed, when pattern matching would be incomplete otherwise...

**SSCCE (Short Self-Contained Correct Example)**
1. Go to https://github.com/kutyel/miin-routine/runs/1651338511?check_suite_focus=true
2. Click on 'Run elm-review' action
3. Scroll down to 'L33'
4. See error:
```sh
(fix) NoUnused.Patterns: Tuple pattern is not needed.

365|         ( _, _ ) ->
             ^^^^^^^^
366|             column [ width fill, centerY, spacing 30 ]

You should remove it at the location I pointed at.
```

**Expected behavior**
If you have a look at the code in https://github.com/kutyel/miin-routine/blob/master/src/Main.elm#L356, it is clear that we are just handling the responsive case for the `Phone` and `Portrait` case, but the rest we do not care, so the empty tuple pattern `(_, _)` is **totally** needed!

**Comment by sparksp** [comment]
Thanks for the report! If you do not care about the rest then the recommended pattern will be simply `_`... is there a reason this would not work for your case?

**Comment by kutyel** [comment]
Yup that is correct, the `_` fixes it, but the error report is mistaken anyway, you get the impression that the pattern is not used and it even offers itself to remove it for you, but this would run into a compiler error! 😉

**Comment by sparksp** [comment]
Hmm, it should only offer to replace `( _, _ )` with `_`, if it offers to remove the entire branch then this is indeed an error.

However, it is clear that the description could be improved - rather than saying "You should remove it at the location I pointed at." it would it be better to say "You can replace it with '_' at this location."?

**Comment by kutyel** [comment]
That's correct, thanks! 🙌🏻

**Comment by kutyel** [comment]
Awesome, thanks for such a quick fix! 🙌🏻
