### ISSUE TITLE
NoUnused.Variable removes the following comment

### ISSUE THREAD

**Issue by jpagex** [jfmengels/elm-review-unused#26]
In some cases (as the following example), the comment following a non-used top variable is removed.

**SSCCE (Short Self-Contained Correct Example)**
When running `elm-review --fix` on the following example (I simplified the real use case):
```elm
module Main exposing (main)

import Api
import AuthToken exposing (AuthToken)
import Html
import Id exposing (Id)
import Task exposing (Task)


main : Html.Html msg
main =
    Html.text "Hello World"



-- SINGLE


get : AuthToken -> Id -> Task Api.Error Event
get token id =
    let
        url =
            ApiUrl.event id

        decoder =
            Decode.field "event" Event.decoder
    in
    Api.get (Just token) url decoder



-- LIST


list : AuthToken -> Task Api.Error (List Event)
list token =
    let
        url =
            ApiUrl.events

        decoder =
            Decode.field "events" (Decode.list Event.decoder)
    in
    Api.get (Just token) url decoder



-- CREATE
```
We get the following proposition:
![Screenshot 2021-01-28 at 21 45 36](https://user-images.githubusercontent.com/635768/106196823-3703c900-61b2-11eb-8d65-2436ba02e0b1.png)

This proposition proposes to remove the following comment which I do not want. In other scenarios, this does not happen.

**Expected behavior**
I would expect only the lines 19-30 to be removed. (Ideally, I would want to remove line 16, but how can `elm-review` know that?)

**Additional context**
`elm-review` CLI version: 2.3.3
`"jfmengels/elm-review": "2.3.8"`
`"jfmengels/elm-review-unused": "1.1.4"`

**Comment by jfmengels** [comment]
Thanks for reporting this :)
It's a known issue, due to a bug in the parser (https://github.com/stil4m/elm-syntax/issues/63). We're going to try publishing a version of that library with a fix soon. I'll close this issue when that happens so you'll be notified :+1:

**Comment by jpagex** [comment]
Great, thanks!

**Comment by jfmengels** [comment]
`elm-syntax` v7.2.0 has been released, and `elm-review` v2.4.1 should support it well. The issue should be fixed now. Feel free to re-open/leave a comment if you encounter this problem again :blush:

**Comment by jpagex** [comment]
Great, thanks for the work and for letting me know!

I tried the new `elm-review` with the new `elm-syntax` and here is what I got:

![Screenshot 2021-02-03 at 22 19 33](https://user-images.githubusercontent.com/635768/106810970-f6062b80-666d-11eb-8a6f-073d972e694e.png)

It should be working fine, but there is something weird about which newlines will be deleted.

**Comment by jfmengels** [comment]
Yeah, that's the diff algorithm that I'm using that does not optimize for "blocks" of code. I'm using https://package.elm-lang.org/packages/jinjor/elm-diff/latest.

I'll create an issue and see if some people would be interested in improving that :+1:
