### ISSUE TITLE
False positive on `NoUnused.Dependencies`

### ISSUE THREAD

**Issue by klaftertief** [jfmengels/elm-review-unused#50]
**Describe the bug**
`elm-review-unused` reports false positive `NoUnused.Dependencies`, seemingly when an indirect dependency has a module with the same name as a module in a direct dependency.

**SSCCE (Short Self-Contained Correct Example)**
1. Go to 'https://github.com/klaftertief/elm-review-unused-sscce'.
2. Clone the repo, install dependencies with `npm install`.
3. Run `npm run sscce`.
4. See that `f0i/iso8601` is falsely reported as unused. It is imported and used in `Main.elm`.

**Expected behavior**
`f0i/iso8601` should not be reported as unused.

**Additional context**
It seems to be that `elm-review-unused` relates the `Iso8601` module with the one from the indirect dependency `rtfeldman/elm-iso8601-date-strings`, which can't be used in user application code.

It's probably caused by turning a list of module and package names into a dictionary here. https://github.com/jfmengels/elm-review-unused/blob/9ea4ce690fd6adca787a23e96f672f84f122bd2b/src/NoUnused/Dependencies.elm#L70-L78
The dictionary uses module names as the key, so a module name can only be related to one package in the current implementation.

**Comment by jfmengels** [comment]
Hi @klaftertief  👋
Thanks for the detailed SSCCE! 🙏
I'll look at this after my holidays (likely next weekend), but I imagine (note to future me) that the fix is to filter out the indirect dependencies and only include the direct dependencies in that dependency dictionary (in the code you linked to).

**Comment by klaftertief** [comment]
I can confirm that filtering out indirect dependencies fixes the issue in our codebase.
