### ISSUE TITLE
Module reported as unused when it contains main

### ISSUE THREAD

**Issue by MartinSStewart** [jfmengels/elm-review-unused#54]
**Describe the bug**
I have a module named `snapshot-runner/SnapshotRunner.elm` located in a Lamdera project. The following error is reported 
```
-- ELM-REVIEW ERROR -------------------- snapshot-runner\SnapshotRunner.elm:1:13

NoUnused.Modules: Module `SnapshotRunner` is never used.

1| port module SnapshotRunner exposing (main)
               ^^^^^^^^^^^^^^

This module is never used. You may want to remove it to keep your project clean,
and maybe detect some unused code in your project.

I found 1 error in 1 file.

```

**Expected behavior**
I'm expecting no error since this module contains a main function.

```elm
main : Program Json.Decode.Value Model Msg
main = ...
```

**Additional context**
Since this is a Lamdera app, the issue might be that NoUnused.Modules is only making an exception for `app` instead of `main` even though `app` is only relevant in `Frontend.elm` and `Backend.elm` (correct me if I'm wrong on this @supermario).

**Comment by supermario** [comment]
Awesome, thanks @jfmengels ! 🎉

**Comment by MartinSStewart** [comment]
Seconded! This means I can now remove an ignored module from one of my projects 😃
