### ISSUE TITLE
Getting a false positive with this rule

### ISSUE THREAD

**Issue by lucamug** [jfmengels/elm-review-unused#57]
I am getting this error:

```elm
-- ELM-REVIEW ERROR --------- src/Api/DataManual/ResponseLoginComplete.elm:19:30

NoUnused.CustomTypeConstructorArgs: Argument is never extracted and therefore
never used.

18|     | ResponseLoginRedirect Api.DataGenerated.ResponseLoginRedirect.ResponseLoginRedirect
19|     | ResponseUserAgreements Api.DataGenerated.ResponseUserAgreements.ResponseUserAgreements
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This argument is never used. You should either use it somewhere, or remove it at
the location I pointed at.

I found 1 error in 1 file.
```

but somewhere else in the code:

```elm
        Flow.State.R92_DeviceFlow_Agreement payload ->
            case Http.Boxed.body boxed of
                Just (Api.CommonRequest.Success (Api.DataManual.ResponseAgree.ResponseUserAgreements bodySuccess)) ->
                   ... using bodySuccess
```

**Comment by jfmengels** [comment]
@lucamug Are you sure these 2 are the same constructor? It looks like `ResponseUserAgreements` in the first extract is in the `Api.DataManual.ResponseLoginComplete` module where the one referenced by the second one is from the `Api.DataManual.ResponseAgree` module.

If these are indeed the same constructor, do you think you could create a SSCCE? I'm having some trouble reproducing the issue.

**Comment by lucamug** [comment]
@jfmengels, thank you for looking into this. I cannot find this anymore in my code, some how it got resolved. So I guess this is not an issue anymore. I will reopen a new issue if I could find it again
