### ISSUE TITLE
Pattern variables starting with _ should not be reported as unused  

### ISSUE THREAD

**Issue by bgrundmann** [jfmengels/elm-review-unused#64]
**What the rule should do:**

At the moment _foo patterns are reported as unused (if the variable _foo is indeed unused). I propose to change that. Prior art: Warning 27 in OCaml.

**What problems does it solve:**

When writing some pattern it is often useful to name the things that were taken apart, to be clear which is which. If if that thing is not used it is nevertheless useful for readability. "oh that is where we do not use the key".  And to make  later changes easier: "okay I need the key ... oh there it is".

**Example of things the rule would not report:**

```elm

Dict.toList d
  |> List.map (\(_key, value) -> value)

-- Or

subscriptions _model = Sub.none
  
```

**Comment by lydell** [comment]
```
Variable names cannot start with underscores like this:

45| subscriptions _model = Sub.none
                  ^^^^^^
You can either have an underscore like _ to ignore the value, or you can have a
name like model to use the matched value.
```

**Comment by bgrundmann** [comment]
Damn you are right I had foolishly thought that the error message came from elm-review and not elm itself. Well I guess I want a language / compiler change then. Which I guess I'll never get... sigh.
