### ISSUE TITLE
False positive "Type constructor `WidgetTac_SubmitForm` is not used." when the message contains an underscore?

### ISSUE THREAD

**Issue by lucamug** [jfmengels/elm-review-unused#65]
I am getting a false positive:

```
NoUnused.CustomTypeConstructors: Type constructor `WidgetTac_SubmitForm` is not
used.
```

But the message is clearly used in other part of the code. For example:

```
        Main.Msg.WidgetTac_SubmitForm ->
            model |> Utils.UpdateHelpers.submitForm
```
Could it be related to the underscore?

Update: Is not related to the underscore (I tried removing it). I still cannot see any pattern. Will keep watching is the false positive eventually disappear. I cannot make a simple example, as this is part of a large app.

**Comment by lucamug** [comment]
It seems that elm-review was actually correct. Moving ahead in the refactoring those messages end up to be removed

**Comment by jfmengels** [comment]
Hey 👋
I'm glad that elm-review ended up being correct. I imagine you misunderstood the error message, or that the error message was not clear enough. I'm curious to know whether you have ideas that would have made it more obvious what this rule meant. What could a more helpful message look like?
