### ISSUE TITLE
Simplify duplicate/nested `as` patterns

### ISSUE THREAD

**Issue by SiriusStarr** [jfmengels/elm-review-unused#72]
**What the rule should do:**

Detect nested `as` patterns and unify them.

**Example of things the rule would report:**

```elm
nestedAs : Int -> ( Int, Int, Int )
nestedAs ((a as b) as c) =
    ( a, b, c )
```
to
```elm
nestedAs : Int -> ( Int, Int, Int )
nestedAs  a =
    ( a, a, a )
```

and

```elm
type Opaque = Opaque Int

nestedAs : Opaque -> ( Int, Opaque, Opaque )
nestedAs (((Opaque a) as b) as c) =
    ( a, b, c )
```
to
```elm
type Opaque = Opaque Int

nestedAs : Opaque -> ( Int, Opaque, Opaque )
nestedAs ((Opaque a) as b) =
    ( a, b, b )
```
 
**To Discuss**

Which name should be preserved?  i.e. `a` or `b` or `c` (or `b or `c` in the latter example) in the above?

**Comments**

These probably aren't likely to be written by hand very much, but they can definitely happen from automated fixes from other `elm-review` rules.  `elm-review-unused` will catch if one of the patterns isn't used at all, but in this case, they are all actually used.

**Comment by jfmengels** [comment]
Alright, I've made it so that `NoUnused.Patterns` reports this issue (as well as `(name as otherName)`) in #73

**Comment by SiriusStarr** [comment]
Excellent; `NoUnused.Patterns` is definitely a better home for it.  I may still try to keep those from being generated in weird fix edge cases, but at least they'll get flagged by some other common rule now.  :+1:
