### ISSUE TITLE
Have NoUnused.Exports report functions only used in tests (and similar folders)

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-unused#80]
## Goal

Report code that is unused in theory but present in tests (and similar places like styleguides, etc.)

## Fails

```elm
module A exposing (someFunction)

someFunction n = n + 1
```

```elm
module ATest exposing (suite)

import A
import Expect
import Test exposing (test)

suite =
  test "should return 2" <|
    \() ->
      someFunction 1
        |> Expect.equal 2
```

If we see references to `someFunction` **only** in tests, then it's in practice unused in the codebase, and we are testing unused code. If we remove both the tests and the function, then there will be no impact on the codebase.

This would help detect even more unused code and reduce the amount of maintenance needed when changing related code.

At work, we often uncover unused functions that fit these characteristics but that were not being reported by `NoUnused.Exports`.

## Idea

Add a configuration option to the `NoUnused.Exports` rule. By default (without the option) we will have today's behavior, where we report only unreferenced exports.
This configuration option that allows ignoring the usages from specific places (using a glob or a filter function, TBD).

That will help detect code that is only used in tests but is never used elsewhere in practice.
The rule will not automatically remove the exports detected in “ignored” locations, as that would create compiler errors (the tests need to be removed for instance), it would only report them.

The problem with this approach, is that this is going to report too many functions.
In some codebases, some functions are exported **to enable tests**. For instance, imagine you have a type that you can only create through a complex JSON decoder. For the sake of nicer tests, you have created a helper function that creates that type from scratch, and that you only use in tests (there should probably be another rule to enforce that).
So given this situation, if we ignore tests, the test helper functions will get reported but that would be false positive, as you in practice need them.

So we need some way to detect which functions are used as helper functions, and which ones are regular functions. I don’t think we can find a way to detect in which category a function false (ideas welcome, this would be awesome to have!).

My current suggestion is to have an annotation. So either in the function’s documentation such as `@helper` (in the same way that `@docs` work) or in the name (with a suffix like `__TEST`). For the documentation approach, we could hardcode (or default) that to `@helper` but make that customisable.

In the error message, we'd tell people that they can add a helper tag to ignore this report.

## API suggestion

```elm
NoUnused.Exports.defaults
  |> NoUnused.Exports.ignoreUsagesIn
     { files = [ "some-*-glob.elm", "tests/" ] -- to be refined
       -- or using a function
       filePredicate = (\{filePath, moduleName} -> if filePath.startsWith "tests/" || filePath.endsWith "Example")
     , helperTags = [ "@helper", "@example" ] -- Trigger a configuration error if they don't start with "@"
     }
  |> NoUnused.Exports.rule
```

**Comment by r-k-b** [comment]
In our codebase, we export a record named `exportedForTests` that contains the test-only functions and values.
