### ISSUE TITLE
NoUnused.Exports does not work when exposing all

### ISSUE THREAD

**Issue by tfausak** [jfmengels/elm-review-unused#82]
**Describe the bug**
I'm not sure if this is a bug. Perhaps I don't understand how this rule is supposed to work. At any rate, if you use `NoUnused.Exports.rule` and also expose everything using `exposing (..)`, the rule won't fire.

**SSCCE (Short Self-Contained Correct Example)**
Define a module like this:

``` elm
module Example exposing (..)

unused : ()
unused =
    ()
```

**Expected behavior**
A warning that `unused` is in fact unused. Changing `exposing (..)` to `exposing (unused)` does give the warning:

> Exposed function or value `unused` is never used outside this module.

**Additional context**
I noticed this while developing an application where we've decided to always use `exposing (..)` in order to avoid the busywork of managing exports. After a while, I noticed that things I knew were unused weren't being reported as such by elm-review. It took me a while to discover that `exposing (..)` was the culprit.

**Comment by tfausak** [comment]
I think there is something actionable though: You can delete the declaration. 

If I wasn't using `exposing (..)`, then elm-review would warn about the exposed declaration being unused. So I could remove it from the `exposing` list. After doing that, elm-review would again warn me about an unused and unexposed top-level declaration. 

I think the behavior I'm looking for is for elm-review to treat `exposing (..)` the same as explicitly exposing every identifier in the module.

**Comment by jfmengels** [comment]
> I think there is something actionable though: You can delete the declaration.

That is interesting. This would cause the rule to behave a bit like `NoUnused.Variables` in practice.The only thing I'm worried about is whether this is over-stepping the bounds of the rule, mostly in a way that will cause problems to people. For instance, you could

> I think the behavior I'm looking for is for elm-review to treat exposing (..) the same as explicitly exposing every identifier in the module.

The difference is in how the fix will be applied
